spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  application:
    name: mall-thirdpart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 30000

qiniu:
  bucket: cloud-mall-saltlee
  accessKey: t8JIzWuyA-33x8Tlt-pdsPFz5wugZAue4NLFY4Lr
  secretKey: MN5v9XHTWtZsMYI0Dcjqk5U--H4bhI1TnISWKJ9K
#  url: http://qgjbfbc2u.hn-bkt.clouddn.com/
  url: http://cloud-mall-oss.saltlee.cn/
