server:
  port: 30000
spring:
  application:
    name: mall-cart
  thymeleaf:
    cache: false
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.3
