server:
  port: 25001
spring:
  application:
    name: mall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.3
  session:
    store-type: redis #整合springsession
  rabbitmq:
    host: 192.168.56.3
    port: 5672
    virtual-host: /
  task:
    execution:
      pool:
        core-size: 20
        max-size: 50
  thymeleaf:
    cache: false
