spring:
  application:
    name: mall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848     #nacos服务注册中心地址
  redis:
    host: 192.168.56.3
    port: 6379
  thymeleaf:
    cache: false
  session:
    store-type: redis  #整合springsession

server:
  port: 20000

  servlet:
    session:
      timeout: 30m   #session过期时间

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

